trigger:
- main

pool: 'skagent'
  # vmImage: ubuntu-latest

steps:
- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: 'print ("Hello world")'
  displayName: 'Run a Python script'
  # inputs:
  #   scriptSource: 'inline'
  #   script: |
  #     versionSpec: '3.8'
  #         installationPath: 'C:\Python38'
  #       displayName: 'Install Python 3.8'